version: 1.0.dev{build}
environment:
  matrix:
    - PYTHON: "C:\\Python36"
    - PYTHON: "C:\\Python36-x64"
install:
  - '%PYTHON%\\python.exe -m pip install -U pip'
  - '%PYTHON%\\python.exe -m pip install -U wheel setuptools'
  - '%PYTHON%\\python.exe -m pip install -U -r requirements-dev.txt'
  - '%PYTHON%\\python.exe -m pip install -e .'
build: false
test_script:
  - '%PYTHON%\\python.exe -m pytest -m "not integration"'
